.TH "QSPEAKERS" "1" 
.SH "NAME" 
qspeakers \(em simulate common loudspeaker enclosures 
.SH "SYNOPSIS" 
.PP 
\fBqspeakers\fR [file.qsp]  
.SH "DESCRIPTION" 
.PP 
This manual page documents the \fBqspeakers\fR program. 
.PP 
\fBqspeakers\fR is a graphical program that simulates common loudspeaker enclosures 
such as sealed-system, ported-system and symmetric bandpass-system. 
 
.PP 
\fBqspeakers\fR displays the expected frequency response curve of a system, given 
the loudspeaker Thiele / Small parameters and the enclosure parameters. 
 
.\" created by instant / docbook-to-man 
